### ISSUE TITLE
This is a bogus crack. 

### ISSUE THREAD

**Issue by PinkEyeRep** [STIZZY801/BrowneyeV2#1]
PinkEye V2.0 is not only an obsolete and no longer functional program, but is already free and released to the general public. This individual did not even change the name of the file contained to BrownEye, which in itself doesn't make sense. They blatantly ripped PinkEye and are attempting to take credit for an already released and free program that is obsolete, putting the users of their program at risk. Long and short, this person is a scammer putting people's PCs at risk.

**Comment by STIZZY801** [comment]
"this person is a scammer putting people's PCs at risk." this is ripped code from you guys so if anyones pc get messed up it be from your guys code. all i did was unpack and get the src also this a joke i dont expect anyone to use/download. its a shit post.

**Comment by PinkEyeRep** [comment]
Your 'shit post' is putting people's PC and accounts at risk should they attempt to compile and build your completely illegible 'shit post'.

**Comment by STIZZY801** [comment]
that's on them not me

**Comment by PinkEyeRep** [comment]
It's totally on you for putting the bogus crack build up. You're putting a loaded gun in the middle of a school and then saying it's on the kids for any shootings.

**Comment by STIZZY801** [comment]
Bro, they should strive to make wise decisions.
not my doing brotha

**Comment by PinkEyeRep** [comment]
You actively endorse unwise decisions by putting a publicly obsolete build up under a new name and then tell people that it's their fault for not seeing how dangerous that is, as well as making it more difficult to produce a v3 by publicly posting the v2 rip allowing any Rockstar devs to dissect it. That's certainly a strategy.

**Comment by STIZZY801** [comment]
That's a good point about the v3. Not that r* would see this but never know. I didn't think of that. It was funny for a bit but I didn't think about that. was a shit post but made a good point

**Comment by PinkEyeRep** [comment]
I appreciate your open-mindedness and retrospect. Shit posts are funny, and I agree on the value of them, but it's not quite as funny when the post contains potentially essential information to the continued success of PinkEye implementations.

**Comment by STIZZY801** [comment]
Was supposed to be oh haha that's funny and I did get the reactions  I wanted but that v3 thing is a very good point I didn't think about. and how bad that would be if a r* dev saw or BE seen it or someone reported it to them and it could mess things up. This wasn't supposed to be an attack on pink dev or malicious just a shit post now I think of posting src was a SUPER bad idea could of not posted src and just renamed the file/loader and sent a pic
